// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: coin.proto

package pro

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CoinClient is the client API for Coin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoinClient interface {
	ForwardTransaction(ctx context.Context, in *TransactionWithAddress, opts ...grpc.CallOption) (*Empty, error)
	ForwardBlock(ctx context.Context, in *Block, opts ...grpc.CallOption) (*Empty, error)
	// Establishes a one way connection to a node (may be reciprocated)
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*Empty, error)
	// Gets maximum 500 blocks past block with top hash
	GetBlocks(ctx context.Context, in *GetBlocksRequest, opts ...grpc.CallOption) (*GetBlocksResponse, error)
	// Get a single block
	GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error)
	// Sends know addresses to neighbors, forwarded from node to node
	SendAddresses(ctx context.Context, in *Addresses, opts ...grpc.CallOption) (*Empty, error)
	// Gets neighbor addresses from node (can be multicast with static addr_me)
	GetAddresses(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Addresses, error)
	// Segwit protocol; added for Lightning
	GetWitnesses(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Witnesses, error)
}

type coinClient struct {
	cc grpc.ClientConnInterface
}

func NewCoinClient(cc grpc.ClientConnInterface) CoinClient {
	return &coinClient{cc}
}

func (c *coinClient) ForwardTransaction(ctx context.Context, in *TransactionWithAddress, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Coin/ForwardTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coinClient) ForwardBlock(ctx context.Context, in *Block, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Coin/ForwardBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coinClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Coin/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coinClient) GetBlocks(ctx context.Context, in *GetBlocksRequest, opts ...grpc.CallOption) (*GetBlocksResponse, error) {
	out := new(GetBlocksResponse)
	err := c.cc.Invoke(ctx, "/Coin/GetBlocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coinClient) GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error) {
	out := new(GetDataResponse)
	err := c.cc.Invoke(ctx, "/Coin/GetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coinClient) SendAddresses(ctx context.Context, in *Addresses, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Coin/SendAddresses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coinClient) GetAddresses(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Addresses, error) {
	out := new(Addresses)
	err := c.cc.Invoke(ctx, "/Coin/GetAddresses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coinClient) GetWitnesses(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Witnesses, error) {
	out := new(Witnesses)
	err := c.cc.Invoke(ctx, "/Coin/GetWitnesses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoinServer is the server API for Coin service.
// All implementations must embed UnimplementedCoinServer
// for forward compatibility
type CoinServer interface {
	ForwardTransaction(context.Context, *TransactionWithAddress) (*Empty, error)
	ForwardBlock(context.Context, *Block) (*Empty, error)
	// Establishes a one way connection to a node (may be reciprocated)
	Version(context.Context, *VersionRequest) (*Empty, error)
	// Gets maximum 500 blocks past block with top hash
	GetBlocks(context.Context, *GetBlocksRequest) (*GetBlocksResponse, error)
	// Get a single block
	GetData(context.Context, *GetDataRequest) (*GetDataResponse, error)
	// Sends know addresses to neighbors, forwarded from node to node
	SendAddresses(context.Context, *Addresses) (*Empty, error)
	// Gets neighbor addresses from node (can be multicast with static addr_me)
	GetAddresses(context.Context, *Empty) (*Addresses, error)
	// Segwit protocol; added for Lightning
	GetWitnesses(context.Context, *Transaction) (*Witnesses, error)
	mustEmbedUnimplementedCoinServer()
}

// UnimplementedCoinServer must be embedded to have forward compatible implementations.
type UnimplementedCoinServer struct {
}

func (UnimplementedCoinServer) ForwardTransaction(context.Context, *TransactionWithAddress) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardTransaction not implemented")
}
func (UnimplementedCoinServer) ForwardBlock(context.Context, *Block) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardBlock not implemented")
}
func (UnimplementedCoinServer) Version(context.Context, *VersionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedCoinServer) GetBlocks(context.Context, *GetBlocksRequest) (*GetBlocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlocks not implemented")
}
func (UnimplementedCoinServer) GetData(context.Context, *GetDataRequest) (*GetDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedCoinServer) SendAddresses(context.Context, *Addresses) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAddresses not implemented")
}
func (UnimplementedCoinServer) GetAddresses(context.Context, *Empty) (*Addresses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddresses not implemented")
}
func (UnimplementedCoinServer) GetWitnesses(context.Context, *Transaction) (*Witnesses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWitnesses not implemented")
}
func (UnimplementedCoinServer) mustEmbedUnimplementedCoinServer() {}

// UnsafeCoinServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoinServer will
// result in compilation errors.
type UnsafeCoinServer interface {
	mustEmbedUnimplementedCoinServer()
}

func RegisterCoinServer(s grpc.ServiceRegistrar, srv CoinServer) {
	s.RegisterService(&Coin_ServiceDesc, srv)
}

func _Coin_ForwardTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionWithAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinServer).ForwardTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Coin/ForwardTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinServer).ForwardTransaction(ctx, req.(*TransactionWithAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coin_ForwardBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Block)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinServer).ForwardBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Coin/ForwardBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinServer).ForwardBlock(ctx, req.(*Block))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coin_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Coin/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coin_GetBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinServer).GetBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Coin/GetBlocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinServer).GetBlocks(ctx, req.(*GetBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coin_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Coin/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinServer).GetData(ctx, req.(*GetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coin_SendAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Addresses)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinServer).SendAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Coin/SendAddresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinServer).SendAddresses(ctx, req.(*Addresses))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coin_GetAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinServer).GetAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Coin/GetAddresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinServer).GetAddresses(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coin_GetWitnesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinServer).GetWitnesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Coin/GetWitnesses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinServer).GetWitnesses(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

// Coin_ServiceDesc is the grpc.ServiceDesc for Coin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Coin",
	HandlerType: (*CoinServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ForwardTransaction",
			Handler:    _Coin_ForwardTransaction_Handler,
		},
		{
			MethodName: "ForwardBlock",
			Handler:    _Coin_ForwardBlock_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _Coin_Version_Handler,
		},
		{
			MethodName: "GetBlocks",
			Handler:    _Coin_GetBlocks_Handler,
		},
		{
			MethodName: "GetData",
			Handler:    _Coin_GetData_Handler,
		},
		{
			MethodName: "SendAddresses",
			Handler:    _Coin_SendAddresses_Handler,
		},
		{
			MethodName: "GetAddresses",
			Handler:    _Coin_GetAddresses_Handler,
		},
		{
			MethodName: "GetWitnesses",
			Handler:    _Coin_GetWitnesses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coin.proto",
}

// LightningClient is the client API for Lightning service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LightningClient interface {
	// Establishes a one way connection to a node (may be reciprocated)
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*Empty, error)
	// Have to actually set up the channel
	OpenChannel(ctx context.Context, in *OpenChannelRequest, opts ...grpc.CallOption) (*OpenChannelResponse, error)
	// send pre-signed state n + 1, receive it back signed by counterparty with revocation key for state n
	GetUpdatedTransactions(ctx context.Context, in *TransactionWithAddress, opts ...grpc.CallOption) (*UpdatedTransactions, error)
	// Once everyone has state n + 1, you can safely revoke state n
	GetRevocationKey(ctx context.Context, in *SignedTransactionWithKey, opts ...grpc.CallOption) (*RevocationKey, error)
}

type lightningClient struct {
	cc grpc.ClientConnInterface
}

func NewLightningClient(cc grpc.ClientConnInterface) LightningClient {
	return &lightningClient{cc}
}

func (c *lightningClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Lightning/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightningClient) OpenChannel(ctx context.Context, in *OpenChannelRequest, opts ...grpc.CallOption) (*OpenChannelResponse, error) {
	out := new(OpenChannelResponse)
	err := c.cc.Invoke(ctx, "/Lightning/OpenChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightningClient) GetUpdatedTransactions(ctx context.Context, in *TransactionWithAddress, opts ...grpc.CallOption) (*UpdatedTransactions, error) {
	out := new(UpdatedTransactions)
	err := c.cc.Invoke(ctx, "/Lightning/GetUpdatedTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightningClient) GetRevocationKey(ctx context.Context, in *SignedTransactionWithKey, opts ...grpc.CallOption) (*RevocationKey, error) {
	out := new(RevocationKey)
	err := c.cc.Invoke(ctx, "/Lightning/GetRevocationKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LightningServer is the server API for Lightning service.
// All implementations must embed UnimplementedLightningServer
// for forward compatibility
type LightningServer interface {
	// Establishes a one way connection to a node (may be reciprocated)
	Version(context.Context, *VersionRequest) (*Empty, error)
	// Have to actually set up the channel
	OpenChannel(context.Context, *OpenChannelRequest) (*OpenChannelResponse, error)
	// send pre-signed state n + 1, receive it back signed by counterparty with revocation key for state n
	GetUpdatedTransactions(context.Context, *TransactionWithAddress) (*UpdatedTransactions, error)
	// Once everyone has state n + 1, you can safely revoke state n
	GetRevocationKey(context.Context, *SignedTransactionWithKey) (*RevocationKey, error)
	mustEmbedUnimplementedLightningServer()
}

// UnimplementedLightningServer must be embedded to have forward compatible implementations.
type UnimplementedLightningServer struct {
}

func (UnimplementedLightningServer) Version(context.Context, *VersionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedLightningServer) OpenChannel(context.Context, *OpenChannelRequest) (*OpenChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenChannel not implemented")
}
func (UnimplementedLightningServer) GetUpdatedTransactions(context.Context, *TransactionWithAddress) (*UpdatedTransactions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUpdatedTransactions not implemented")
}
func (UnimplementedLightningServer) GetRevocationKey(context.Context, *SignedTransactionWithKey) (*RevocationKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRevocationKey not implemented")
}
func (UnimplementedLightningServer) mustEmbedUnimplementedLightningServer() {}

// UnsafeLightningServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LightningServer will
// result in compilation errors.
type UnsafeLightningServer interface {
	mustEmbedUnimplementedLightningServer()
}

func RegisterLightningServer(s grpc.ServiceRegistrar, srv LightningServer) {
	s.RegisterService(&Lightning_ServiceDesc, srv)
}

func _Lightning_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightningServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Lightning/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightningServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightning_OpenChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightningServer).OpenChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Lightning/OpenChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightningServer).OpenChannel(ctx, req.(*OpenChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightning_GetUpdatedTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionWithAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightningServer).GetUpdatedTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Lightning/GetUpdatedTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightningServer).GetUpdatedTransactions(ctx, req.(*TransactionWithAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightning_GetRevocationKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedTransactionWithKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightningServer).GetRevocationKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Lightning/GetRevocationKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightningServer).GetRevocationKey(ctx, req.(*SignedTransactionWithKey))
	}
	return interceptor(ctx, in, info, handler)
}

// Lightning_ServiceDesc is the grpc.ServiceDesc for Lightning service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Lightning_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Lightning",
	HandlerType: (*LightningServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Lightning_Version_Handler,
		},
		{
			MethodName: "OpenChannel",
			Handler:    _Lightning_OpenChannel_Handler,
		},
		{
			MethodName: "GetUpdatedTransactions",
			Handler:    _Lightning_GetUpdatedTransactions_Handler,
		},
		{
			MethodName: "GetRevocationKey",
			Handler:    _Lightning_GetRevocationKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coin.proto",
}
